PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT ?Source ?Target ?Label
WHERE { ?Source ?Label ?Target
       FILTER (?Label = skos:inScheme || ?Label = skos:narrower ) }
ORDER BY ?Source